### ISSUE TITLE
error on npm install after cloning

### ISSUE THREAD

**Issue by fopsdev** [MangoTools/sean#1]
hi there

after cloning and running npm install i get the following eeror after a while:

npm ERR! sean@0.1.1 postinstall: `bower install --config.interactive=false`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sean@0.1.1 postinstall script.
npm ERR! This is most likely a problem with the sean package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:

if tried this because the yo sean approach didn't work as well for me

i will check back here earliest next week.
project looks promising

**Comment by jean-baptiste-blanc** [comment]
Hey,

just run Bower install (this happen when bower finds multiple possible prerequisite for a module.

JB
